# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/mithorium-common-graphics/LA.UM.9.6.3.r1-06200-89xx.0/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/mititanium-common-graphics/LA.UM.10.6.2.r1-01600-89xx.0

PRODUCT_COPY_FILES += \
    vendor/xiaomi/mititanium-common-graphics/LA.UM.10.6.2.r1-01600-89xx.0/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \

PRODUCT_PACKAGES += \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    libC2D2 \
    libCB \
    libOpenCL \
    libadreno_utils \
    libc2d30_bltlib \
    libgsl \
    libllvm-glnext \
    vulkan.adreno \
    libdisp-aba \
    libhdr_tm \
    libscalar \
    libsdedrm \
    libsdm-color \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmextension \
    libtinyxml2_1 \
    vendor.display.color@1.0 \
    vendor.display.postproc@1.0 \
    vendor.display.color@1.0-service \
    mm-pp-dpps
